---
# ==========================================================================
# Variáveis Globais
# Arquivo: group_vars/all.yml
#
# - Este arquivo contém variáveis globais, que podem ser usadas 
#   em todos os hosts e grupos definidos no arquivo de inventário.
# - As variáveis são organizadas por host ou grupo de hosts, permitindo que as 
#   configurações sejam facilmente localizadas e modificadas conforme necessário.
# ==========================================================================

# kvm-win11
win11_kvm_public_ip : 192.168.0.110
win11_kvm_ansible_user : user1
win11_kvm_ansible_password : password1

# dell_n5010-n5010-win10
win10_dell_n5010_public_ip : 192.168.0.111
win10_dell_n5010_ansible_user : user2
win10_dell_n5010_ansible_password : password2

# amd-fx8350-win11
win11_amd_fx8350_public_ip : 192.168.0.112
win11_amd_fx8350_ansible_user : user3
win11_amd_fx8350_ansible_password : password3

# pm-winsrv
winsrv2k22_pm_public_ip : 192.168.0.200
winsrv2k22_pm_ansible_user : Administrator
winsrv2k22_pm_ansible_password : password4
