# ===============================================================
# Inventário de Hosts e Grupos
# Arquivo: inventory/hosts.yml
# ===============================================================

all:
  children:

    win11_kvm_zabbix_agent:
      hosts:
        kvm-win11:
          ansible_host: "{{ win11_kvm_public_ip }}"
      vars:
        ansible_user: "{{ win11_kvm_ansible_user }}"
        ansible_password: "{{ win11_kvm_ansible_password }}"
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 60
        ansible_winrm_read_timeout_sec: 90

    win10_dell_n5010_zabbix_agent:
      hosts:
        dell-n5010-win10:
          ansible_host: "{{ win10_dell_n5010_public_ip }}"
      vars:
        ansible_user: "{{ win10_dell_n5010_ansible_user }}"
        ansible_password: "{{ win10_dell_n5010_ansible_password }}"
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 60
        ansible_winrm_read_timeout_sec: 90

    win11_amd_fx8350_zabbix_agent:
      hosts:
        amd-fx8350-win11:
          ansible_host: "{{ win11_amd_fx8350_public_ip }}"
      vars:
        ansible_user: "{{ win11_amd_fx8350_ansible_user }}"
        ansible_password: "{{ win11_amd_fx8350_ansible_password }}"
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 60
        ansible_winrm_read_timeout_sec: 90

    winsrv2k22_pm_zabbix_agent:
      hosts:
        pm-winsrv2k22:
          ansible_host: "{{ winsrv2k22_pm_public_ip }}"
      vars:
        ansible_user: "{{ winsrv2k22_pm_ansible_user }}"
        ansible_password: "{{ winsrv2k22_pm_ansible_password }}"
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 60
        ansible_winrm_read_timeout_sec: 90